# -*- coding: utf-8 -*-
"""SportVsBahia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i9GvOazuPZ4P5-odpympzY05WrrLIkYo
"""
import yaml

with open('./utils/sportVSbahia.yaml', 'r', encoding='utf8') as file:
    dados = yaml.safe_load(file)

dados

sport = {}
bahia = {}

for ano, dado in dados.items():
    for time, pontos in dado.items():
        soma = sum(v if v is not None else 0 for v in pontos.values())
        if time == 'Sport':
            sport[ano] = soma
        elif time == 'Bahia':
            bahia[ano] = soma

print("ANO  | SPORT | BAHIA | VENCEU")
for ano in dados.keys():
    emoji = "🦁 SPT" if sport[ano] > bahia[ano] else "🦸‍♂️ BAH"
    print(f"{ano} |  {sport[ano]:02d}   |  {bahia[ano]:02d}   |  {emoji}")

vitorias_sport = sum(1 for ano in dados.keys() if sport[ano] > bahia[ano])
vitorias_bahia = sum(1 for ano in dados.keys() if bahia[ano] > sport[ano])

print(f"Sport venceu {vitorias_sport} vezes.")
print(f"Bahia venceu {vitorias_bahia} vezes.")

total_sport = sum(sport.values())
total_bahia = sum(bahia.values())

print(f"Sport fez um total de {total_sport} pontos.")
print(f"Bahia fez um total de {total_bahia} pontos.")

# prompt: divida os dados do sport e bahia por decada

sport_por_decada = {}
bahia_por_decada = {}

for ano, dado in dados.items():
    decada = str(ano)[:3] + '0s'
    sport_pontos = sum(v if v is not None else 0 for k, v in dado.items() if k == 'Sport' for v in v.values())
    bahia_pontos = sum(v if v is not None else 0 for k, v in dado.items() if k == 'Bahia' for v in v.values())

    if decada not in sport_por_decada:
        sport_por_decada[decada] = 0
        bahia_por_decada[decada] = 0

    sport_por_decada[decada] += sport_pontos
    bahia_por_decada[decada] += bahia_pontos

print("\nPontos por década:")
print("DECADA | SPORT | BAHIA | VENCEDOR DA DECADA")
for decada in sorted(sport_por_decada.keys()):
    sport_total = sport_por_decada[decada]
    bahia_total = bahia_por_decada[decada]
    vencedor_decada = "🦁 Sport" if sport_total > bahia_total else "🦸‍♂️ Bahia" if bahia_total > sport_total else "🤝 Empate"
    print(f"{decada}  |  {sport_total:02d}   |  {bahia_total:02d}   | {vencedor_decada}")

vitorias_decada_sport = sum(1 for decada in sport_por_decada.keys() if sport_por_decada[decada] > bahia_por_decada[decada])
vitorias_decada_bahia = sum(1 for decada in sport_por_decada.keys() if bahia_por_decada[decada] > sport_por_decada[decada])

print(f"\nSport venceu {vitorias_decada_sport} décadas.")
print(f"Bahia venceu {vitorias_decada_bahia} décadas.")

import matplotlib.pyplot as plt
import numpy as np

# Dados de exemplo
x = [int(ano) for ano in dados.keys()]
sport_pts = [ponto for ponto in sport.values()]
bahia_pts = [ponto for ponto in bahia.values()]

# Criar gráfico de linha
plt.plot(x, sport_pts, label='Sport', color='r')
plt.plot(x, bahia_pts, label='Bahia', color='b')

# Adicionar título e rótulos
plt.title('Desempenho Sport VS Bahia')
plt.xlabel('Ano')
plt.ylabel('Pontos')

plt.legend()
plt.xticks(x, rotation=90, fontsize=9)
plt.tight_layout()
# Exibir o gráfico
plt.show()

sport_br = {}
bahia_br = {}

for ano, dado in dados.items():
    for time, pontos in dado.items():
        soma = pontos['Brasileirão']
        if time == 'Sport':
            sport_br[ano] = soma
        elif time == 'Bahia':
            bahia_br[ano] = soma

# Dados de exemplo
x = [int(ano) for ano in dados.keys()]
sport_pts = [ponto for ponto in sport_br.values()]
bahia_pts = [ponto for ponto in bahia_br.values()]

# Criar gráfico de linha
plt.plot(x, sport_pts, label='Sport', color='r')
plt.plot(x, bahia_pts, label='Bahia', color='b')

# Adicionar título e rótulos
plt.title('Desempenho Sport VS Bahia (Brasileirão)')
plt.xlabel('Ano')
plt.ylabel('Pontos')

plt.legend()
plt.xticks(x, rotation=90, fontsize=9)
plt.tight_layout()
# Exibir o gráfico
plt.show()

sport_cdb = {}
bahia_cdb = {}

for ano, dado in dados.items():
    for time, pontos in dado.items():
        soma = pontos['Copa_Brasil']
        if time == 'Sport':
            sport_cdb[ano] = soma
        elif time == 'Bahia':
            bahia_cdb[ano] = soma

# Dados de exemplo
anos = [int(ano) for ano in dados.keys()]
sport_pts = [ponto for ponto in sport_cdb.values()]
bahia_pts = [ponto for ponto in bahia_cdb.values()]

sport_pts = [ponto if ponto is not None else 0 for ponto in sport_pts]
bahia_pts = [ponto if ponto is not None else 0 for ponto in bahia_pts]

x = np.arange(len(anos))
largura = 0.4

# Criar gráfico de linha
plt.bar(x - largura/2, sport_pts, width=largura, label='Sport', color='r')
plt.bar(x + largura/2, bahia_pts, width=largura, label='Bahia', color='b')

# Adicionar título e rótulos
plt.title('Desempenho Sport VS Bahia (Copa do Brasil)')
plt.xlabel('Ano')
plt.ylabel('Pontos')

plt.legend()
plt.xticks(x, anos, rotation=90, fontsize=9)
plt.tight_layout()
# Exibir o gráfico
plt.show()